// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcOgd2sF3dRhMbZmgTmLR2Pr3hzySbbFs',
    appId: '1:542925608787:web:aa5d6bbe935f25e2e8b3a6',
    messagingSenderId: '542925608787',
    projectId: 'sportsz-ea6f3',
    authDomain: 'sportsz-ea6f3.firebaseapp.com',
    storageBucket: 'sportsz-ea6f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIK-En0p8wcOO0dVUuXPNX6zSfrTeV1v8',
    appId: '1:542925608787:android:63882b05125e2621e8b3a6',
    messagingSenderId: '542925608787',
    projectId: 'sportsz-ea6f3',
    storageBucket: 'sportsz-ea6f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzDJ2udZ3W3NuBaulXu2zAhKfNKIxwcRg',
    appId: '1:542925608787:ios:1e290d98d050bdbde8b3a6',
    messagingSenderId: '542925608787',
    projectId: 'sportsz-ea6f3',
    storageBucket: 'sportsz-ea6f3.firebasestorage.app',
    iosBundleId: 'com.sportsz.sportsz',
  );
}
